### PR TITLE
Add Apcu cache driver

### PR DESCRIPTION
**Pull request by declic3000**

### CODE REVIEW

**Comment by moust** [comment]
Could you add unit tests for this driver please ?

**Comment by declic3000** [comment]
Yes I can, Quentin

Guillaume Wauquier - Développeur web - Déclic3000
06 95 33 42 59 - http://www.declic3000.com/

**Comment by declic3000** [comment]
Hello Quentin,
Did you have some time to look into this ?
Let me know
Have a good

**Comment by moust** [comment]
Thanks a lot for this work :)

**Pull request merged**
